<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_table'][0] 	= 'Tabelle';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_table'][1] 	= 'Wählen Sie die Quelltabelle';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_key'][0]		= 'Schlüsselfeld';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_key'][1]		= 'Bitte wählen Sie das Feld, das als eindeutige Referenz genutzt werden soll. Standard ist das ID Feld';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_value'][0]	= 'Wertefeld';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_value'][1]	= 'Bitte wählen Sie das Feld, das als Quelle für die Werte dienen soll.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_sorting'][0]	= 'Sortierfeld';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_sorting'][1]	= 'Bitte wählen Sie das Feld nachdem die Auswahl sortiert werden soll. Alternativ kann die Sortierung über das Bedingungsfeld gesetzt werden.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_where'][0]	= 'Bedingung';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_where'][1]	= 'Hier können Sie eine Bedingung eingeben, um die Ergebnisse zu filtern (z.B. published=1)';	
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_custom'][0]	= 'Eigene Quelle';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_custom'][1]	= 'Wählen Sie hier, wenn Sie ein andere Tabelle als die Standard-Tags-Tabelle (pct_customelement_tags) als Quelle nutzen wollen.';	
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_roots'][0]	= 'Auswahl einschränken';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_roots'][1]	= 'Wählen Sie die Tags die mit Ihren Kindelementen angezeigt werden sollen.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_translations'][0]	= 'Übersetzungsfeld';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_translations'][1]	= 'Wählen das Feld, was als Übersetzungsquelle dient. Das Feld sollte durch ein Übersetzungswidget-Attribut erstellt sein oder ein metaWizard Feld';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['tags'] = array('Attribut-Optionen','Wählen Sie welche zusätzlichen Optionen dargestellt werden sollen.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['tags']['sortable']	= 'Individuelle Reihenfolge';
