<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Config Label
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['config']['label'] 	= 'Tags'; 

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['title'][0]			= 'Bezeichnung';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['title'][1]			= 'Bitte geben Sie einen Text ein.';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['translations'][0]		= 'Übersetzungen';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['translations'][1]		= 'Bitte geben Sie die Übersetzung ein.';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['translations']['label'] = 'Bezeichnung';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['title_legend']		= 'Bezeichnung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['new']        			= array('Neues Tag', 'Einen neues Tag anlegen.');
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['edit'][0]				= 'Tag bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['edit'][1]				= 'Tag ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['copy'][0]				= 'Tag kopieren';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['copy'][1]				= 'Tag ID %s kopieren';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['delete'][0]			= 'Tag entfernen';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['delete'][1]			= 'Soll das Tag ID %s entfernt werden?';