<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_table'][0] 	= 'Table';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_table'][1] 	= 'Choose the source table';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_key'][0]		= 'Key field';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_key'][1]		= 'Please choose the field that should be the unique reference to the value. Default is ID';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_value'][0]	= 'Value field';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_value'][1]	= 'Please choose the field that contains the values';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_sorting'][0]	= 'Sort field';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_sorting'][1]	= 'Please choose the field that is the sorting reference.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_where'][0]	= 'Conditions';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_where'][1]	= 'Here you can enter conditions that filter the result (e.g. published=1)';	
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_custom'][0]	= 'Custom source';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_custom'][1]	= 'Select here if you want to use a different table as the source.';	
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_roots'][0]	= 'Limitation';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_roots'][1]	= 'Limit the selection to the selected elements and their childs.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_translations'][0]	= 'Translations-widget';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['tag_translations'][1]	= 'Select the field that stores the translations e.g. created by the translations-widget attribute. Or by a metaWizard field';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['tags'] = array('Attribute options','Choose more options');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['tags']['sortable']	= 'Custom order';
