<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Config Label
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['config']['label'] 	= 'Tags'; 

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['title'][0]			= 'Title';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['title'][1]			= 'Please enter a unique title.';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['translations'][0]		= 'Translations';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['translations'][1]		= 'Bitte enter the translation.';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['translations']['label'] = 'Term';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['title_legend']		= 'Title';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['new']        			= array('New Tag', 'Create a new tag.');
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['edit'][0]				= 'Edit entry';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['edit'][1]				= 'Edit entry ID %s';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['copy'][0]				= 'Copy entry';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['copy'][1]				= 'Copy entry ID %s';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['delete'][0]			= 'Delete entry';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['delete'][1]			= 'Delete entry ID %s ?';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['copyChilds'][0]		= 'Copy tag ID %s including child elements';
$GLOBALS['TL_LANG']['tl_pct_customelement_tags']['copyChilds'][1]		= 'Copy tag ID %s including child elements';
